### ISSUE TITLE
GitHub repo for @kbrandwijk/swagger-to-graphql ?

### ISSUE THREAD

**Issue by mohawk2** [graphql-binding/graphql-binding-openapi#1]
I found yarax's one a while ago, and used it to start https://github.com/graphql-perl/GraphQL-Plugin-Convert-OpenAPI . The `t` directory there contains all the corpus it handles so far, several of which broke yarax's version. I would be interested to see where yours is at, and/or to unify these projects with something a bit more declaratively OpenAPI -> GraphQL-y.

**Comment by kbrandwijk** [comment]
Mine lives here: https://github.com/supergraphql/swagger-to-graphql. The only thing I changed in my fork is being able to pass in the endpoint. There's an open PR on the main repo to move back to it when it's merged.

**Comment by fabien0102** [comment]
@kbrandwijk If you talk about this PR https://github.com/yarax/swagger-to-graphql/pull/50 I think that we can go back to the official npm package here :wink:

**Comment by kbrandwijk** [comment]
Not exactly, the other big change was about the `viewer` field that I didn't want to use (as it was more geared towards Relay, and the Graphcool/Prisma way wasn't). It is mentioned here: https://github.com/yarax/swagger-to-graphql/issues/49#issuecomment-361067417, and didn't get approval from @yarax.

**Comment by yarax** [comment]
great, thank you

**Comment by Urigo** [comment]
Thank you for reporting.

In the last few months, since [the transition of many libraries](https://www.prisma.io/blog/the-guild-takes-over-oss-libraries-vvluy2i4uevs) under [The Guild](http://the-guild.dev)'s leadership, We've reviewed and released many improvements and versions to [graphql-cli](https://github.com/Urigo/graphql-cli), [graphql-config](https://github.com/kamilkisiela/graphql-config) and [graphql-import](https://github.com/ardatan/graphql-import).

We've reviewed `graphql-binding`, had many meetings with current users and engaged the community also through the [roadmap issue](https://github.com/dotansimha/graphql-binding/issues/325).

What we've found is that the new [GraphQL Mesh](https://the-guild.dev/blog/graphql-mesh) library is covering not only all the current capabilities of GraphQL Binding, but also the future ideas that were introduced in the [original GraphQL Binding blog post](https://github.com/prisma-archive/prisma-blog-archive/blob/master/2018-01-12-reusing-and-composing-graphql-apis-with-graphql-bindings.mdx) and haven't come to life yet.

And the best thing - [GraphQL Mesh](https://the-guild.dev/blog/graphql-mesh) gives you all those capabilities, even if your source is not a GraphQL service at all!  
it can be GraphQL, OpenAPI/Swagger, gRPC, SQL or any other source!
And of course you can even merge all those sources into a single SDK.

Just like GraphQL Binding, you get a fully typed SDK (thanks to the protocols SDKs and the [GraphQL Code Generator](https://github.com/dotansimha/graphql-code-generator)), but from any source, and that SDK can run anywhere, as a connector or as a full blown gateway.
And you can share your own "Mesh Modules" (which you would probably call "your own binding") and our community already created many of those!
Also, we decided to simply expose regular GraphQL, so you can choose how to consume it using all the awesome [fluent client SDKs out there](https://hasura.io/blog/fluent-graphql-clients-how-to-write-queries-like-a-boss/).

If you think that we've missed anything from GraphQL Binding that is not supported in a better way in GraphQL Mesh, please let us know!
